"""Emit the system's magic-data.mjs from the verified rulebook extract.

Generated, not hand-copied, for the same reason chargen-data.mjs is: the
sheet must be showing provably the same Bind/Strand/Convocation/Fraying data
that parse_magic.py verified verbatim against the book text.
"""
import json

m = json.load(open("data/magic.json"))

js = f"""/* GENERATED by build_magic_data.py from data/magic.json. Do not hand-edit:
 * parse_magic.py verified every name, cost and quote below against the Core
 * Rulebook text before this file was emitted. Re-run those two scripts to
 * regenerate.
 *
 * Deliberately NOT everything data/magic.json holds. The Shaping and Spell
 * Effect cost tables and the Weave Reaction Table are used by the macro pack,
 * which carries its own baked TBE_MAGIC block, and by the generated Weave
 * Magic journal -- not by any sheet or DataModel. Exporting them here would
 * ship ~1100 lines that nothing in the system module reads, which is the same
 * "goes nowhere" problem as a dead button, just quieter. */

/** The five Binds (Ch.14). Real percentile skills, rolled like any other. */
export const BINDS = {json.dumps([b["name"] for b in m["binds"]])};
export const BIND_INFO = {json.dumps(m["binds"], indent=2)};

/** The ten Strands. NOT percentile skills: a 1-to-10+ level track that helps
 *  cover a spell's Total Cost rather than being rolled. */
export const STRANDS = {json.dumps([s["name"] for s in m["strands"]])};
export const STRAND_INFO = {json.dumps(m["strands"], indent=2)};

/** The twelve established Convocations, each a template of 2 Binds,
 *  4 Strands and 2 Thin Strands (Ch.7 p.106). */
export const CONVOCATIONS = {json.dumps(m["convocations"], indent=2)};

/** Fraying: the rules constants and the four symptom tiers (p.308-309). */
export const MAGIC_RULES = {json.dumps(m["rules"], indent=2)};
export const FRAYING_SYMPTOMS = {json.dumps(m["frayingSymptoms"], indent=2)};
"""

out = "system/the-broken-empires/module/helpers/magic-data.mjs"
open(out, "w").write(js)
print("wrote", out, round(len(js) / 1024, 1), "KB;",
      len(m["binds"]), "Binds,", len(m["strands"]), "Strands,",
      len(m["convocations"]), "Convocations")
