"""Emit the system's chargen-data.mjs from the verified rulebook extracts.

Generated rather than hand-copied so the system's size/race/career tables are
provably the same data that chargen.py verified against the book text.
"""
import json

c = json.load(open("data/chargen.json"))

races = [{
    "name": r["name"], "d100": r["d100"], "size": r["size"],
    "toughness": r["toughness"], "dt": r["dt"],
    "lethalityBonus": r["lethalityBonus"], "toughnessCap": r["toughnessCap"],
    "skillMods": r["skillMods"],
    "savvy": r["savvy"],
    "languages": r["languages"],
    "exclusiveTalents": r["exclusiveTalents"],
    "restrictions": r["restrictions"],
    "bonus": r["bonus"],
    "startingSkills": r.get("startingSkills", []),
    "talentLimits": r.get("talentLimits", []),
} for r in c["races"]]

js = f"""/* GENERATED by build_system_data.py from the rulebook extract. Do not hand-edit:
 * every value here was verified verbatim against the Core Rulebook text by
 * chargen.py before being emitted. Re-run that script to regenerate. */

/** Ch.18 Size ladder, smallest to largest. Medium is the human baseline. */
export const SIZES = {json.dumps(c["sizes"])};
export const MEDIUM_SIZE = {c["mediumIndex"]};

/** Stat deltas per Size step, applied ONLY when a creature's size is CHANGED
 *  from its starting size. Bestiary stat blocks already account for their own
 *  size, so these must never be re-applied just for being Large. */
export const SIZE_STEP_EFFECTS = {json.dumps(c["sizeStepEffects"], indent=2)};

/** Combat effects of the Size DIFFERENCE between two combatants (Ch.18).
 *  These always apply, whatever the creature's origin. */
export const SIZE_COMBAT_RULES = {json.dumps(c["sizeCombatRules"], indent=2)};

/** The six playable races (Ch.5), with the numbers the macros actually apply. */
export const RACES = {json.dumps(races, indent=2)};

/** The ten Previous Careers (Ch.7). A career is a one-time chargen budget:
 *  once its points are spent nothing reads it again, so it is applied by the
 *  Create Character window rather than tracked as a live stat. */
export const CAREERS = {json.dumps(c["careers"], indent=2)};

export const TALENT_CATEGORIES = ["Combat", "Adventuring", "Social", "Lore", "Magic", "Miscellaneous", "Non-Human"];
"""
out = "system/the-broken-empires/module/helpers/chargen-data.mjs"
open(out, "w").write(js)
print("wrote", out, round(len(js) / 1024, 1), "KB;",
      len(c["sizes"]), "sizes,", len(races), "races,", len(c["careers"]), "careers")
