/* Regenerates the standalone, pre-compiled single-file macro exports in
 * output/ — the same payload build.js bakes into the installer's macro
 * list for "TBE: Character Wizard" and "TBE: Build Character", just
 * written out individually so they can be pasted directly into a Foundry
 * Script Macro without running the full installer. Mirrors build.js's own
 * NEEDS_TABLES/NEEDS_CHARGEN logic exactly -- neither macro needs the
 * oracle table data (NEEDS_TABLES), both need the chargen data. */
const fs = require("fs");
const path = require("path");

const lib = fs.readFileSync(path.join(__dirname, "macros/_lib.js"), "utf8");
const chargen = JSON.parse(fs.readFileSync(path.join(__dirname, "data/chargen.json"), "utf8"));
const talents = JSON.parse(fs.readFileSync(path.join(__dirname, "data/talents.json"), "utf8"));
const CHARGEN_DATA = "const TBE_CHARGEN = " + JSON.stringify(chargen) + ";\n" +
  "const TBE_TALENTS = " + JSON.stringify(talents) + ";\n";
const EMPTY_DATA = "const TBE_DATA = { tables: [] };\n";

const HEADER = (name) => `/* ${name} -- compiled standalone macro for The Broken Empires (Foundry VTT).
 * Paste this whole file into a new Script macro and run it. Self-contained:
 * no companion data files or other macros required. Regenerated by
 * regen_output.js from macros/_lib.js + data/chargen.json + data/talents.json
 * + the macro's own source, matching exactly what build.js bakes into the
 * full TBE-Solo-Installer.js bundle for this macro. */
`;

const TARGETS = [
  { name: "TBE: Character Wizard", file: "tbe-character-wizard.js", out: "TBE-Character-Wizard.js" },
  { name: "TBE: Build Character", file: "tbe-build-character.js", out: "TBE-Build-Character.js" }
];

for (const t of TARGETS) {
  const src = fs.readFileSync(path.join(__dirname, "macros", t.file), "utf8");
  const compiled = HEADER(t.name) + EMPTY_DATA + CHARGEN_DATA + lib + "\n" + src;
  const outPath = path.join(__dirname, "output", t.out);
  fs.writeFileSync(outPath, compiled);
  console.log("wrote", t.out, (compiled.length / 1024).toFixed(1) + " KB");
}
