# Paraphrased from Into the Wyrd and Wild (private use; all rights reserved by the publisher). Names are the book's; descriptions are mine.
LOCATIONS = [
"Abbey to the Godflesh: a rotting abbey; living flesh of a god pulses on the altar and warps reality nearby",
"Abstersion Pool: a crystal pool made from a god's tear; cleanses ailments; two elder dryads judge who may bathe",
"Ale Spring: a cold spring of lager",
"Altioc's Grave: sickly oaks over piled ancient warriors, weapons standing like saplings",
"Bathing Pools: hot-spring pools on a poplar hill; the waters have an odd property",
"Bauik Hive: forested mountains, foul smell, deep cracks; sweet voices call from the tunnels",
"Bliss Fields: thick sweet green mist, tall grass, dead barkless trees; hard to see",
"Boreal Woods: vast pine, spruce and larch wood; resin smell, needle-crunch",
"Bramble Maze: a thorn maze that shifts when unwatched and feeds on flesh",
"Bristlepine Grove: ancient stunted pines on a scree slope, older than memory",
"Broken Shrine: shattered druid altar; something ended it all in one night",
"Cairn of the First Hunters: stone pile, each stone scratched with a prehistoric beast",
"Cenotaph to a Dead Seraph: a monument carved with a hundred lines of script; a divine beast fell here",
"Cliffface Amphitheater: terraced bowl under a concave cliff with perfect acoustics",
"Clonal Forest: one tree, one root, one will, for miles; it expects respect",
"Collector's Statue Garden: rag-wrapped Collector wanders among alabaster statues of mortals in terror",
"Council of Blind Archmages: five ruined, blind, lonely archmages who will talk at length",
"Darkly Lake: salt-and-pepper beach, emerald-dark water",
"Deciduous Growth: ordinary thick hardwood forest, busy with small animals",
"Desolate Crater: blasted bowl where a meteor fell; ash remains buried at the centre",
"Devil's Garden: only larch and crabgrass grow; demonic sprites poisoned the rest",
"Dwelling of the Scroll Man: hermit Gallinade carves words from his skin each day; they regrow",
"Elk Haven: a safe creek-side grove for an elk herd",
"Enormous Owl Statue: a huge ivy-grown owl statue with an alien gaze",
"Exile's Camp: a lawless camp of renegades and criminals; tradeable if you are careful",
"Fairy Grove: concentric tree rings around a mushroom ring; tiny fey at their business",
"Fester Pond: stinking green pond with flies; things lurk in the sludge",
"Fields of Silence: grass dotted with dead pines; no sound can be made; a hunter's ideal ambush",
"The Fisher King's River: a black trench river; corpses tangle in hungry roots",
"Foetid Garden: pulp ground, rot, slimes and molds that cling and breed sickness",
"Fossil Graveyard: a collapsed slope of fossils, small and enormous",
"Fruit Trees of Rotten Truth: maggoty fruit; eating it gives a few useless facts, and more",
"Fungal Carpet: dark, spongy fungus floor; corroded gear of the digested",
"Giant Spider Web: silver webs and bones; the spiders will bargain for passage",
"Glowlight Swamp: foggy marsh, drifting bodies, lights that are lures",
"Gorm's Flesh Weald: the ground, trees and roots turn to flesh and vein",
"The Great Honey Comb: cat-sized bees and an enormous hive in a hillside fissure",
"The Grove of Tea and Candles: candle-lit trees and a campfire of reverent tea-lovers",
"Grove of the Millennia Trees: tower-sized trees, eternal dark, whole communities in the branches",
"Hearthstone of Frost: freezing ruined hall; one runed stone cursed by a slighted god",
"Hungry Ground: tiny human mouths in the soil clicking and biting",
"Hysterical Hermit: a mad, shouting hermit with something to trade",
"Idol of Bones: a tree-like heap of bones that speaks plans into your sleep",
"Infectious Scrawl-Stone: touching it covers you in cursed tattoos",
"Ire Briar: low briar that lashes when you show anger, and feeds on it",
"Jeweled Trees: silver-leaved trees with gem nodules in the trunks",
"Junkyard: a gorge heaped with ruined common goods and scavengers",
"Kaleidescopic Trail: a straight trail that refracts into splits and reflections the deeper you go",
"Knowledgeable Knotgrass: sleeping in it brings dreams of history and philosophy",
"Kudzu-ville: a village strangled and sculpted by kudzu",
"Lair of the Mega-Raccoon: a blood-rimmed cave of a legendary beast; you were warned",
"Log Hollow: fallen giant logs hollowed into tunnels held by skulking predators",
"Lost Fortress: an empty keep with its furnishings intact, as if left overnight",
"Mead Tree: a hollow oak full of fine mead; tapping it carries a small risk of collapse",
"Megacolony Mound: a bark-stripped mound of loam and insects; the queen has a plan",
"Megalith Circle: concentric granite slabs aligned to the stars, worn petroglyphs",
"Mirror Copse: trees repeat exactly; something moves off the path; perhaps a duplicate of you",
"Mocking Ossuary: skulls in wall-holes insult you, and know things",
"Moebius Creek: a freezing creek that loops back to its start",
"Moot of the Treefolk: treefolk elders on a hilltop deciding the Wilds' direction; they may ask for a task",
"Mossbed: thick moss over everything; disturbed spores choke the air",
"Mushroom Forest: house-sized mushrooms, glowing at night",
"Muulifan's Myconid Farm: a mirthful grub tends rows of every mushroom, magic or mundane",
"Old Growth: a primordial, root-like, hungry growth draining colour and air",
"Owl Gryphon Lair: a mountaintop nest of carcasses; a giant owl-gryphon sleeps by day, with eggs",
"Palace of Antlers: a gorge palace of stacked antlers; its mad hunter stalks the halls",
"Pete's Shack: a legendary moonshiner's hill shack, rival of Petunia",
"Petrified Forest: stone trees marked by something that lived when they did",
"Petroglyph Cove: a river cave you reach by swimming under a cliff into a carved antechamber",
"Petunia's Shack: a legendary moonshiner's hill shack, rival of Pete",
"Pit of Bodies: a pond-sized pit of rendered bodies, grey mud",
"Plummeting Waterfall: a high waterfall and rocky pool",
"Ponderous Silhouette: a cliff that looks like a thinking face from one spot",
"Prehistoric Butte: a sheer volcanic plateau with no handholds; rumour says something is on top",
"Quail God: a dog-sized, gold-lit divine quail with its flock; it brings life where it walks",
"Quarry: a deep marble quarry with a flooded floor, nesting birds, trapped creatures",
"Respite of the Grey Knight: a silent tarnished knight meditating on a mountain of blades",
"Returning Mound: a cherry-crowned mound in a flowering glade; an unflowered tree and something at its base",
"Scrawl Trees: pines carved and painted with thousands of stories by crimson-cloaked carvers",
"Shale Field: treeless splintered shale; a fall cuts to the bone",
"Singer's Domain: a copse without animals; travellers dream of a high hollow song",
"The Slate: roots converge on a huge crude slate megalith",
"Sleeping Linnorm: a vast wyrm asleep like a mossy log; waking it risks its fury",
"Smoldering Woods: ash-black woods crawling with cinder trails; cursed by some power",
"Soot Crag: sooty crag over a burning coal seam venting gas",
"Spike Throne: a thorn-and-bramble throne in a fly-ridden fen",
"Spiral Earthwork: a giant salt-and-stone spiral for some ceremony",
"Switchback River: a slow river that doglegs into rocky rapids",
"Talisman Garden: thousands of hideous charms hung in the canopy, chiming",
"Tar Pits: bubbling asphalt that drags down the heavy; old and new remains",
"Time-warped Weald: plants age and regress in minutes; staying is dangerous",
"Tomb of the First Mortals: a crawlspace tomb of skeletons in primitive jewelry",
"Torpid Marshlands: a stagnant fen; leeches make boats the only way",
"Trees Marked by a Dark Touch: a trail of dead earth and tarry handprints; something terrible passed",
"Vast Mound: a man-made hill, hollow inside, a ritual space",
"Vermin Fields: ground of cracking bones and hiding vermin; best not stay after dark",
"Watching Trees: lone trees whose bark grooves fold open as glassy eyes",
"The Weaver's Den: a woven den of twine and web, previous heroes bricked into its walls, spider-things on patrol",
"Wyrd Stones: carved shale pillars; a caster studying them a week learns their secrets",
"Yaruinne's Haven: a dragon impaled on a tree, healed around it; she holds court and sells knowledge of great beasts",
]
assert len(LOCATIONS)==100, len(LOCATIONS)

TRAILS = [
"wide path dusted with coal ash and black sand","crumbling knee-high stone wall","pale cobbles that are skulls","path paved with legible gravestones",
"narrow trail gouged by hooves","overgrown old road of broken cobble","trail edged with faintly glowing mushrooms","path along the buried spine of a colossal corpse",
"steep mossy switchbacks up a cliff","lifeless path smelling of sulfur and blood","narrow damp fissure like a scar","twisting flood-gouged track",
"loam canyon walled with twitching roots","marble steps lit by bronze braziers","knotted carpet of vine","moldy boardwalks through a rancid fen",
"felled trees laid flat as a walkway","aged suspension bridge over a misty gorge","former creek, now muddy and fly-ridden","crushed quartz path that glitters",
"deer path with salt-licks and snares","road through a deserted village with watching eyes","terrace tunnel of spider web and dried bodies","sandstone trail lined with monstrous totems",
"strangely straight trail with echoing voices","hot path of smouldering embers","crumbling battlement of a great wall used as a path","wood slats etched with poems",
"ferry pier and raft run by a robed figure who takes secrets as payment","trail made by a carpet of ants that ignore you","small weathered trail beside a stream","trail strewn with broken glass and mirrors",
"standing stones with greedy faces as markers","whistling bird leads through a thicket","trail of laid-out weapons and armour","giant frog offers a ride across a poison swamp",
"through the mouth and gullet of a sleeping linnorm","trail of rusted pennies winding round trees","ancient stone staircase down a wooded gulch","trail of decapitated animals into the dark",
"trees carved with the same unnerving symbol",
"cathedral ruins whose archways mark the path","skeletons hanging from nooses line the trail","nithing poles bearing skulls mark a footpath","ivy-covered aqueduct used as a road","slimy path of an impossibly large slug that smells of wet paint","footpath carved by deliberate burning","river ford marked by defaced statues of dead gods","silent robed monks pointing the way","untouched kingly road, clearly ancient",
]
BODY = [
"lice combs and soap","glass jar of teeth","torches of limb, root and bone","coins with face and mint scratched off","squirming sack holding an infant Wild Elf",
"knucklebone dice","arrows tipped with a great beast's molars","petrified head of an ancient druid","crude phrasebook of Fangspek","dark carnivore hides",
"wreath of useful plants","tinderboxes with dry tinder","used cast-iron skillet","aged purple wood mask with scrawl","mud-coated goat jerky",
"jug of spirits with a dead mouse","holy book with pressed leaves","fancy helmet whose faceplate won't stay up","pipe-weed and a stained oak pipe","two silver compasses pointing different ways",
"jugs of sulfur-smelling water","heraldic patchwork quilt","stoneware crock with a hideous face","bag of Sanctified Salt","tin cage with an unruly Quilluff",
"necklace of wooden sigils for reading scrawl","sack of dead, bright-plumed birds","wool-and-cotton blankets","envelope of disease-marked scabs","basket of edible mushrooms",
"necklace of severed fingers","a Wild Elf treasure","fragment of a spellbook with one spell","patchwork backpack","bone-handled knives, rusty but sharp",
"pocket map of the local area","journal of a dead adventurer, with secrets","rope of human and animal hair","broken-in leather gloves","vellum sheets made from human skin",
"poem in Rhymespeak about hidden treasure","woodcutter's axe with 23 handle notches","burlap sack of oats","wool cloak with patches of adventuring bands","battered shield with a fighting snail",
"dark children's tales about the Wilds","ironwood walking stick","scrawl-etched bone charms","antler deer-call whistle","tin-and-wood birdcall",
]
assert len(TRAILS)==50 and len(BODY)==50

NAME_PREFIX = ["Aviary","Backwoods","Bog","Burial Ground","Burrows","Canyon","Cliffs","Conifers","Copse","Cradle","Crater","Den","Evergreens","Fen","Flowerbed","Forest","Garden","Gorges","Graveyard","Greenlands","Grove","Haven","Hearth","Hills","Hive","Hunting Grounds","Marsh","Maze","Mire","Mound","Mountain","Nest","Old-Growth","Orchard","Primeval Woods","Remains","Road","Rotfields","Ruins","Sporebed","Swamps","Thicket","Timberline","Trail","Valley","Weald","Wetlands","Wildlands","Woodland","Woods"]
NAME_SUFFIX = ["of Absolution","of Anguish","of Awakening","of Blades","of Bloodshed","of Bones","of Bounty","of Broken Time","of Burning","of Corpses","of Dead Gods","of Dead Kings","of Decay","of Desolation","of Disease","of Drowning","of Druids","of Eternal Dreams","of Euphoria","of Filth","of Fool's Gold","of Hunger","of Madness","of Mutation","of Night","of Nightmares","of Poison","of Regret","of Rime","of Sacrifice","of Silence","of Singing","of Snares and Traps","of Spores","of Standing Stones","of Storms","of the Ancients","of the Behemoth","of the Crows","of the Flesh","of the Lost","of the Megalith","of the Mother","of the Ritual","of the Totems","of the Void","of Trickery","of Vermin","of Worms","of Wraiths"]
assert len(NAME_PREFIX)==50 and len(NAME_SUFFIX)==50
DANGER = [
"feral knights patrol in pairs","sleep brings nightmares of an unholy shrine","ravagers hunt travellers for sport","a monstrous intelligent spider's home","it snatches corpses and the fallen",
"canopy so thick it is total darkness","the ground heaves and hungers for flesh","robs adventurers at every turn","travel is mostly up cliff faces","game and flora are diseased",
"the wildlife hunts together","a mad druid holds a primal deity's name","far too easy to get lost","a false god demands worship","magic and spells have lives of their own",
"the dead do not stay dead","no fire or lamp will burn","rust eats metal fast","it takes eyes and ears","the trees and flora conspire against you",
"a fiend lives in the shadows","a gibbering cult demands sacrifice","no one leaves unscathed","regular flooding","a crazed bard rules a ruined keep",
"apparent shelters are always trapped","nighttime ambushes are common","private hunting ground of a Wild Elf lord","memories are hard to keep","one spark starts a wildfire",
"trails change course every full moon","vampylfs have infected every beast","it knows your darkest desires","thick sinking mud everywhere","tolls are paid in fingers",
"it hates and destroys holy symbols","at least one traveller always goes mad","loud noises rouse a primordial beast","wyrd flares cause mutation and worse","loners are always captured",
"music is punished","everyone is a backstabber and liar","time flows in many directions","trust what you hear, never what you see","tests strength in brutal ways",
"easy to enter, hard to leave","trails and paths are ambush spots","it enjoys riddles and punishes the unclever","deadly chill at night","it always takes one life",
]
SECRET = [
"a tree that makes horrid but perfect predictions","a way to gain immortality","the name of a powerful primal deity","gold statues","a mage's ancient spellbooks",
"the location of the Wilds' beating heart","blueprints for terrible magic weapons","a way to control the Wyrd briefly","a legendary dryadi craftsman's workshop","standing stones that show the future",
"a way to travel back in time","a saint's relic bones","mythic iron armour buried with its champion","a grimoire listing every mortal's sins","the invulnerable pelt of an ancient wolf god",
"the last writings of a warrior-poetess","a magic forge fuelled by flesh and bone","spider-silk made by the first arachnids","an insane bard's maddening songbook","a long-held secret of the Lady of Broken Branches",
"a dark ritual able to change the world's fate","a sure way to bring back the dead","a legendary warrior's teachings","a way to command mortals with one word","a brazier whose fire never goes out",
"the body of a forgotten deity","a painting hidden for its terrible beauty","the tomb of a legendary civilization","flesh of a divine being","knowledge of every trail and where it goes",
"a bow that calls storm clouds and lightning","a way to keep the mind while the body decays","a portal of shadow and ivy to the afterlife","an ironwood chest with a sleeping godling","the tower of a demigod who weeps sapphire",
"the name of a watchful living star","an important, long-forgotten memory","a song that wins any heart","a flower that cures any ailment","a way to kill The Ruin",
"a crown worth more than any castle","a key that opens anything, not only locks","the sarcophagus of an ancient hero","the cure for Treewylding","a forgotten library of powerful tomes",
"where a falling star last landed","a barbarian king's buried riches","an heirloom that spells disaster for a ruler","a terrible truth about a noble line","a deity's loving embrace",
]
assert len(DANGER)==50 and len(SECRET)==50
