/* GENERATED by build_system_data.py from the rulebook extract. Do not hand-edit:
 * every value here was verified verbatim against the Core Rulebook text by
 * chargen.py before being emitted. Re-run that script to regenerate. */

/** Ch.18 Size ladder, smallest to largest. Medium is the human baseline. */
export const SIZES = ["Minute", "Diminutive", "Tiny", "Little", "Small", "Medium", "Large", "Huge", "Massive", "Gargantuan", "Colossal"];
export const MEDIUM_SIZE = 5;

/** Stat deltas per Size step, applied ONLY when a creature's size is CHANGED
 *  from its starting size. Bestiary stat blocks already account for their own
 *  size, so these must never be re-applied just for being Large. */
export const SIZE_STEP_EFFECTS = {
  "toughness": 1,
  "baseDamage": 2,
  "deathThreshold": 5,
  "initiative": -1
};

/** Combat effects of the Size DIFFERENCE between two combatants (Ch.18).
 *  These always apply, whatever the creature's origin. */
export const SIZE_COMBAT_RULES = [
  {
    "gap": 2,
    "key": "reach",
    "text": "+1 Reach per 2 Sizes larger than the opponent"
  },
  {
    "gap": 2,
    "key": "grapple",
    "text": "Grappling is only possible up to 2 Sizes larger or smaller"
  },
  {
    "gap": 2,
    "key": "might",
    "text": "+20 Might per Size category of difference when Grappling"
  },
  {
    "gap": 3,
    "key": "maneuvers",
    "text": "Drive Back, Trip and Disarm cannot be used against a creature 3+ Sizes larger"
  },
  {
    "gap": 3,
    "key": "monstrous",
    "text": "Melee attacks from a creature 3+ Sizes larger cannot be parried, only Dodged"
  },
  {
    "gap": 3,
    "key": "easyToHit",
    "text": "All Combat skills used against a creature 3+ Sizes larger are at +20"
  }
];

/** The six playable races (Ch.5), with the numbers the macros actually apply. */
export const RACES = [
  {
    "name": "Human",
    "d100": "01-70",
    "size": "Medium",
    "toughness": 0,
    "dt": 20,
    "lethalityBonus": 0,
    "toughnessCap": null,
    "skillMods": [],
    "savvy": [
      "one bonus Savvy skill of their choice"
    ],
    "languages": [
      {
        "name": "cultural Language of the region",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [],
    "restrictions": [],
    "bonus": "One additional level of Expertise in any skill, and one additional Talent for which they meet the requirements.",
    "startingSkills": [],
    "talentLimits": []
  },
  {
    "name": "Half-Orc",
    "d100": "71-80",
    "size": "Medium",
    "toughness": 1,
    "dt": 20,
    "lethalityBonus": 0,
    "toughnessCap": null,
    "skillMods": [
      {
        "skill": "Willpower",
        "mod": -10
      }
    ],
    "savvy": [
      "Endurance"
    ],
    "languages": [
      {
        "name": "Orcish",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [
      "Blood-Fury"
    ],
    "restrictions": [
      "Few if any Half-Orcs will be from the Civilized: Urban background.",
      "Always male. Initial social encounters are uneasy affairs at best."
    ],
    "bonus": "",
    "startingSkills": [],
    "talentLimits": []
  },
  {
    "name": "Dwarf",
    "d100": "81-90",
    "size": "Medium",
    "toughness": 0,
    "dt": 20,
    "lethalityBonus": 1,
    "toughnessCap": null,
    "skillMods": [
      {
        "skill": "Endurance",
        "mod": 10
      },
      {
        "skill": "Inspire",
        "mod": -10
      }
    ],
    "savvy": [
      "Locks & Traps"
    ],
    "languages": [
      {
        "name": "Kharzhad",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [
      "Dwarven Swordsinger"
    ],
    "restrictions": [],
    "bonus": "Reduce the required SLs of any extended Craft: Practical or Craft: Artistic roll by 2.",
    "startingSkills": [],
    "talentLimits": []
  },
  {
    "name": "Ogre",
    "d100": "91-95",
    "size": "Large",
    "toughness": 1,
    "dt": 22,
    "lethalityBonus": 0,
    "toughnessCap": null,
    "skillMods": [
      {
        "skill": "Might",
        "mod": 10
      },
      {
        "skill": "Stealth",
        "mod": -20
      },
      {
        "skill": "Athletics",
        "mod": -20
      },
      {
        "skill": "Melee: Light",
        "mod": -20
      }
    ],
    "savvy": [],
    "languages": [
      {
        "name": "Tusker",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [
      "Devouring Maw"
    ],
    "restrictions": [
      "Ogres may not take any Civilized background.",
      "Can only use Medium or Large shields.",
      "Untrained in reinforced leather, mail, scale or plate: -20 to all Willpower rolls if worn.",
      "May never become any type of Spellweaver or Fade.",
      "Armor Training can be taken only once, giving training in Bone armor only.",
      "The Breaking: on a critical failure using Resolve, attacks the nearest living thing at +10."
    ],
    "bonus": "8 general Inventory ENC instead of 6.",
    "startingSkills": [],
    "talentLimits": [
      {
        "talent": "Armor Training",
        "maxRanks": 1,
        "note": "Bone armor only"
      }
    ]
  },
  {
    "name": "Bolg Fiir",
    "d100": "96-99",
    "size": "Medium",
    "toughness": 0,
    "dt": 20,
    "lethalityBonus": 0,
    "toughnessCap": 2,
    "skillMods": [
      {
        "skill": "Stealth",
        "mod": -10
      },
      {
        "skill": "Insight",
        "mod": -10
      }
    ],
    "savvy": [
      "Melee: Light",
      "Missile",
      "Ancient Lore",
      "Arcana",
      "Naturewise"
    ],
    "languages": [
      {
        "name": "Fionnan (Low Court)",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [
      "Whispered Inheritance"
    ],
    "restrictions": [
      "No Bolg Fiir may take the Civilized: Urban background.",
      "No Bolg Fiir can ever have a Toughness of more than 2."
    ],
    "bonus": "With Patterned in the Weave: +10 to one Bind skill. Without it: +10 to all opposed rolls against Weave Magic. Ancestor Communion: a Hard (-20) Willpower roll on an Elven memory stone grants access to its memories.",
    "startingSkills": [],
    "talentLimits": []
  },
  {
    "name": "The Replaced",
    "d100": "00",
    "size": "Medium",
    "toughness": 0,
    "dt": 20,
    "lethalityBonus": 0,
    "toughnessCap": null,
    "skillMods": [],
    "savvy": [
      "one bonus Savvy skill of their choice (as Human)"
    ],
    "languages": [
      {
        "name": "Language of their cultural region",
        "value": 70
      },
      {
        "name": "Low Vestrian",
        "value": 20
      }
    ],
    "exclusiveTalents": [
      "Hunted By The Queen",
      "Thornmark"
    ],
    "restrictions": [
      "Replaced can never be Spellweavers or Fades.",
      "Must take the Hunted by the Queen Talent (free, mandatory at creation)."
    ],
    "bonus": "Start with 20 in a specialty Lore skill, Dark Fae-wise. Gets all the Traits of a Human.",
    "startingSkills": [
      {
        "name": "Dark Fae-wise",
        "value": 20
      }
    ],
    "talentLimits": []
  }
];

/** The ten Previous Careers (Ch.7). A career is a one-time chargen budget:
 *  once its points are spent nothing reads it again, so it is applied by the
 *  Create Character window rather than tracked as a live stat. */
export const CAREERS = [
  {
    "name": "Warrior",
    "d10": 1,
    "pools": {
      "Combat": 80,
      "Adventuring": 50,
      "Social": 40,
      "Lore": 30,
      "Magic": 0
    },
    "customs": [
      [
        1,
        20
      ]
    ],
    "talents": "Armor Training III, and one Combat Talent",
    "silver": "1d6*5",
    "desc": "Mercenaries, knights, archers, pirates, bandits, and anyone who lives by the sword.",
    "talentPicks": {
      "auto": [
        "Armor Training III"
      ],
      "picks": [
        {
          "count": 1,
          "categories": [
            "Combat"
          ]
        }
      ]
    }
  },
  {
    "name": "Rogue",
    "d10": 2,
    "pools": {
      "Combat": 50,
      "Adventuring": 70,
      "Social": 50,
      "Lore": 30,
      "Magic": 0
    },
    "customs": [
      [
        1,
        20
      ]
    ],
    "talents": "Pick a total of two Talents from the Combat, Adventuring, or Social categories",
    "silver": "1d6*5",
    "desc": "Thieves, assassins, ruffians, burglars, swashbucklers, pirates, and all those who make a living outside the law.",
    "talentPicks": {
      "auto": [],
      "picks": [
        {
          "count": 2,
          "categories": [
            "Combat",
            "Adventuring",
            "Social"
          ]
        }
      ]
    }
  },
  {
    "name": "Ranger",
    "d10": 3,
    "pools": {
      "Combat": 50,
      "Adventuring": 80,
      "Social": 30,
      "Lore": 40,
      "Magic": 0
    },
    "customs": [
      [
        1,
        20
      ]
    ],
    "talents": "On Through the Night or Armor Training I, and any one Combat or Adventuring Talent",
    "silver": "1d6*5",
    "desc": "Warriors of the wilderness, rangers often act as guides for those brave or foolish enough to leave their homes.",
    "talentPicks": {
      "auto": [],
      "picks": [
        {
          "count": 1,
          "named": [
            "On Through the Night",
            "Armor Training I"
          ]
        },
        {
          "count": 1,
          "categories": [
            "Combat",
            "Adventuring"
          ]
        }
      ]
    }
  },
  {
    "name": "Speaker",
    "d10": 4,
    "pools": {
      "Combat": 20,
      "Adventuring": 40,
      "Social": 80,
      "Lore": 60,
      "Magic": 0
    },
    "customs": [
      [
        1,
        30
      ]
    ],
    "talents": "Two Social talents",
    "silver": "2d4*10",
    "desc": "Diplomats, envoys, raconteurs, or anyone who can sway individuals or groups with soaring rhetoric.",
    "talentPicks": {
      "auto": [],
      "picks": [
        {
          "count": 2,
          "categories": [
            "Social"
          ]
        }
      ]
    }
  },
  {
    "name": "Bard",
    "d10": 5,
    "pools": {
      "Combat": 30,
      "Adventuring": 50,
      "Social": 70,
      "Lore": 50,
      "Magic": 0
    },
    "customs": [
      [
        2,
        20
      ]
    ],
    "talents": "Entertaining, and one Social Talent",
    "silver": "1d6*5",
    "desc": "A wandering minstrel, skald, singer, or performer, known for their knowledge of old stories and songs.",
    "talentPicks": {
      "auto": [
        "Entertaining"
      ],
      "picks": [
        {
          "count": 1,
          "categories": [
            "Social"
          ]
        }
      ]
    }
  },
  {
    "name": "Civilian",
    "d10": 6,
    "pools": {
      "Combat": 50,
      "Adventuring": 50,
      "Social": 50,
      "Lore": 50,
      "Magic": 0
    },
    "customs": [
      [
        1,
        20
      ]
    ],
    "talents": "Experienced (during Rounding Out, get an extra 30 points on Adventuring, Social, or Lore skills), and any one Adventuring, Social, or Lore Talent",
    "silver": "2d6*10",
    "desc": "A townsman, guildsman, crafter, farmer, or any other vital role in a pseudo-medieval society.",
    "talentPicks": {
      "auto": [
        "Experienced"
      ],
      "picks": [
        {
          "count": 1,
          "categories": [
            "Adventuring",
            "Social",
            "Lore"
          ]
        }
      ]
    }
  },
  {
    "name": "Loremaster",
    "d10": 7,
    "pools": {
      "Combat": 20,
      "Adventuring": 50,
      "Social": 50,
      "Lore": 80,
      "Magic": 0
    },
    "customs": [
      [
        3,
        30
      ]
    ],
    "talents": "Literate and either Lecturer or Travel Planner",
    "silver": "2d4*10",
    "desc": "A scholar, expert, or wise one well versed in knowledge both esoteric and mundane.",
    "talentPicks": {
      "auto": [
        "Literate"
      ],
      "picks": [
        {
          "count": 1,
          "named": [
            "Lecturer",
            "Travel Planner"
          ]
        }
      ]
    }
  },
  {
    "name": "Merchant",
    "d10": 8,
    "pools": {
      "Combat": 20,
      "Adventuring": 60,
      "Social": 60,
      "Lore": 60,
      "Magic": 0
    },
    "customs": [
      [
        1,
        30
      ]
    ],
    "talents": "Literate, and either Barterer or I See Your Mind",
    "silver": "3d6*10",
    "desc": "Masters of commerce, merchants travel the world (or set up shop) trading wares or services for profit.",
    "talentPicks": {
      "auto": [
        "Literate"
      ],
      "picks": [
        {
          "count": 1,
          "named": [
            "Barterer",
            "I See Your Mind"
          ]
        }
      ]
    }
  },
  {
    "name": "Godbound",
    "d10": 9,
    "pools": {
      "Combat": 30,
      "Adventuring": 40,
      "Social": 50,
      "Lore": 60,
      "Magic": 20
    },
    "customs": [
      [
        1,
        30
      ]
    ],
    "talents": "Godbound, and either Literate or any one Lore Talent",
    "silver": "1d6*10",
    "desc": "A mortal servant chosen by a deity and granted the right to call upon divine aid, provided their Piety is maintained.",
    "talentPicks": {
      "auto": [
        "Godbound"
      ],
      "picks": [
        {
          "count": 1,
          "named": [
            "Literate"
          ],
          "categories": [
            "Lore"
          ],
          "note": "Literate, or any one Lore Talent"
        }
      ]
    }
  },
  {
    "name": "Spellweaver",
    "d10": 10,
    "pools": {
      "Combat": 20,
      "Adventuring": 20,
      "Social": 20,
      "Lore": 40,
      "Magic": 100
    },
    "customs": [
      [
        1,
        20
      ]
    ],
    "talents": "Patterned in the Weave, Literate",
    "silver": "1d6*5",
    "desc": "Wizards, sorcerers, warlocks; a Spellweaver pulls at the threads of reality to work their own will upon it.",
    "talentPicks": {
      "auto": [
        "Patterned in the Weave",
        "Literate"
      ],
      "picks": []
    }
  }
];

export const TALENT_CATEGORIES = ["Combat", "Adventuring", "Social", "Lore", "Magic", "Miscellaneous", "Non-Human"];
