/* GENERATED by build_magic_data.py from data/magic.json. Do not hand-edit:
 * parse_magic.py verified every name, cost and quote below against the Core
 * Rulebook text before this file was emitted. Re-run those two scripts to
 * regenerate.
 *
 * Deliberately NOT everything data/magic.json holds. The Shaping and Spell
 * Effect cost tables and the Weave Reaction Table are used by the macro pack,
 * which carries its own baked TBE_MAGIC block, and by the generated Weave
 * Magic journal -- not by any sheet or DataModel. Exporting them here would
 * ship ~1100 lines that nothing in the system module reads, which is the same
 * "goes nowhere" problem as a dead button, just quieter. */

/** The five Binds (Ch.14). Real percentile skills, rolled like any other. */
export const BINDS = ["Change", "Conjure", "Control", "Destroy", "Witness"];
export const BIND_INFO = [
  {
    "name": "Change",
    "desc": "To alter, to change the basic properties of. An individual\u2014either living being or object\u2014may be made of component parts, but its Essential Pattern is its truest use or most honest expression. A sword has a metal blade ( Earth ), wooden handle ( Plant ), and leather wrappings ( Beast ), but in the end, its true function is about the blade\u2014so its Essential Pattern is Earth . Therefore, casting a spe"
  },
  {
    "name": "Conjure",
    "desc": "To bring forth into being, to create matter from nothing. Individual beings, living or otherwise, cannot be Conjured into existence, but such beings may be healed by this Bind; extra-planar beings may be Summoned. Conjured items last only as long as the spell\u2019s Duration, but their effects may last beyond that."
  },
  {
    "name": "Control",
    "desc": "To manipulate or protect, to take active control. Once a thing is under your control, it remains so until the Duration ends (or until the circumstances change to grant it a new opposed roll). Generally, it takes an action to actively control something or to issue a specific command."
  },
  {
    "name": "Destroy",
    "desc": "To cause harm, to bring an end to. Things destroyed by magic stay destroyed after the spell\u2019s Duration ends; hence, most Destroy spells that do direct or permanent damage have a Duration of Instant, but also have a higher Magnitude to reflect the spell\u2019s destabilizing nature."
  },
  {
    "name": "Witness",
    "desc": "To perceive, to know, to divine, to detect, to scry. Witness spells are often based on what Senses they employ."
  }
];

/** The ten Strands. NOT percentile skills: a 1-to-10+ level track that helps
 *  cover a spell's Total Cost rather than being rolled. */
export const STRANDS = ["Air", "Beast", "Body", "Earth", "Fire", "Plant", "Spheres", "Spirit", "Thought", "Water"];
export const STRAND_INFO = [
  {
    "name": "Air",
    "desc": "Sound, electricity, cold, and light that does not produce heat. Includes invisibility."
  },
  {
    "name": "Beast",
    "desc": "Properties of all creatures, animals, and monsters native to the Broken Empires, and their products (hides, scales, teeth, etc.). Extra-planar creatures like demons fall under Spheres ."
  },
  {
    "name": "Body",
    "desc": "Life, healing, properties of the humanoid physical form. Wounds healed by magic remain healed after the Duration expires."
  },
  {
    "name": "Earth",
    "desc": "Terrestrial materials, minerals, soil, metal, rock, the bones of the earth. Includes gravity."
  },
  {
    "name": "Fire",
    "desc": "Light that produces heat, that which burns. Fire created by magic is normal fire, and burns until it runs out of fuel, the Duration ends, it is put out, or the spell is countered."
  },
  {
    "name": "Plant",
    "desc": "All living plants and materials derived from them."
  },
  {
    "name": "Spheres",
    "desc": "The planes of existence, summoning and binding otherworldly creatures, divining through the constellations, magical transport, the minutiae and esoterica of magic itself."
  },
  {
    "name": "Spirit",
    "desc": "Ghosts and the undead, but also the immortal soul, and spiritual conviction and resistance."
  },
  {
    "name": "Thought",
    "desc": "Minds, dreams, imagination, illusion, knowledge, reason, emotions. When Thought magic\u2019s Duration expires, or if successfully resisted, the target may become aware of the magical manipulation."
  },
  {
    "name": "Water",
    "desc": "Includes precipitation, snow, ice, oceans, rivers, and non-biological liquid. 275 A Spell\u2019s Intention There are many possible approaches to achieving a result through magic. A player should be very specific about their intent behind the magical effect, and how they imagine that spell unfolding. As a caster, I must think: \u201cWhat\u2019s my intent? And which Bind and Strand combination will I use to achiev"
  }
];

/** The twelve established Convocations, each a template of 2 Binds,
 *  4 Strands and 2 Thin Strands (Ch.7 p.106). */
export const CONVOCATIONS = [
  {
    "name": "Aeromancer",
    "binds": [
      "Conjure",
      "Control"
    ],
    "strands": [
      "Air",
      "Earth",
      "Spirit",
      "Thought"
    ],
    "thinStrands": [
      "Beast",
      "Spheres"
    ]
  },
  {
    "name": "Battlemage",
    "binds": [
      "Conjure",
      "Destroy"
    ],
    "strands": [
      "Beast",
      "Body",
      "Earth",
      "Fire"
    ],
    "thinStrands": [
      "Spirit",
      "Thought"
    ]
  },
  {
    "name": "Druid",
    "binds": [
      "Change",
      "Control"
    ],
    "strands": [
      "Beast",
      "Earth",
      "Plant",
      "Water"
    ],
    "thinStrands": [
      "Spheres",
      "Spirit"
    ]
  },
  {
    "name": "Earthbinder",
    "binds": [
      "Change",
      "Control"
    ],
    "strands": [
      "Beast",
      "Air",
      "Earth",
      "Plant"
    ],
    "thinStrands": [
      "Spirit",
      "Thought"
    ]
  },
  {
    "name": "Elementalist",
    "binds": [
      "Conjure",
      "Control"
    ],
    "strands": [
      "Air",
      "Earth",
      "Fire",
      "Water"
    ],
    "thinStrands": [
      "Body",
      "Thought"
    ]
  },
  {
    "name": "Firemancer",
    "binds": [
      "Conjure",
      "Control"
    ],
    "strands": [
      "Air",
      "Fire",
      "Plant",
      "Thought"
    ],
    "thinStrands": [
      "Water",
      "Body"
    ]
  },
  {
    "name": "Healer",
    "binds": [
      "Conjure",
      "Witness"
    ],
    "strands": [
      "Beast",
      "Body",
      "Thought",
      "Water"
    ],
    "thinStrands": [
      "Spheres",
      "Spirit"
    ]
  },
  {
    "name": "Inquisitor of the Order of the Purifying Flame",
    "binds": [
      "Destroy",
      "Witness"
    ],
    "strands": [
      "Body",
      "Fire",
      "Spheres",
      "Spirit"
    ],
    "thinStrands": [
      "Earth",
      "Water"
    ]
  },
  {
    "name": "Seer",
    "binds": [
      "Control",
      "Witness"
    ],
    "strands": [
      "Body",
      "Air",
      "Spheres",
      "Thought"
    ],
    "thinStrands": [
      "Beast",
      "Earth"
    ]
  },
  {
    "name": "Sorcerer",
    "binds": [
      "Control",
      "Destroy"
    ],
    "strands": [
      "Body",
      "Fire",
      "Spheres",
      "Thought"
    ],
    "thinStrands": [
      "Beast",
      "Spirit"
    ]
  },
  {
    "name": "Spiritbinder",
    "binds": [
      "Change",
      "Control"
    ],
    "strands": [
      "Body",
      "Spheres",
      "Spirit",
      "Thought"
    ],
    "thinStrands": [
      "Plant",
      "Fire"
    ]
  },
  {
    "name": "Wavemaster",
    "binds": [
      "Change",
      "Control"
    ],
    "strands": [
      "Air",
      "Beast",
      "Body",
      "Water"
    ],
    "thinStrands": [
      "Fire",
      "Spirit"
    ]
  }
];

/** Fraying: the rules constants and the four symptom tiers (p.308-309). */
export const MAGIC_RULES = {
  "strandRange": [
    1,
    10
  ],
  "strandXpIsNextValue": true,
  "strandXpQuote": "To increase a Strand, spend XP equal to the next highest value.",
  "strandSequentialQuote": "Improvements must be sequential",
  "strandBeyondTenFraying": 1,
  "strandBeyondTenQuote": "for each point a Strand is raised above 10, the Spellweaver gains 1 Fraying.",
  "fadeStrandCap": 7,
  "fadeStrandQuote": "a Fade's Strands can never be developed past 7. Fades are not limited by Thin Strands.",
  "chargenStrandCap": 5,
  "chargenStrandQuote": "No Strand can be developed past level 5 during character creation.",
  "newStrandTalentXp": 5,
  "newThinStrandTalentXp": 10,
  "newStrandQuote": "they may spend 5 XP to acquire the Strand Secret Talent, granting the Strand a starting value of 1. If the Strand is a Thin Strand, the cost is instead 10 XP.",
  "frayingRollQuote": "Roll 1d100. If the result is less than or equal to (Total Fraying - Max Resolve) \u00d7 2, the Spellweaver is forcibly purged from the Tapestry of reality.",
  "frayingIrreversibleQuote": "There is no way of reducing Fraying points,",
  "fadeCritFailFraying": 1,
  "fadeCritFailQuote": "Those with a Faded Pattern accumulate Fraying at an even faster rate: every time they roll a critical failure on a casting roll, they accumulate 1 Fraying point",
  "spellweaverChargen": {
    "binds": 2,
    "strands": 4,
    "thinStrands": 2,
    "bindBonus": 10,
    "magicPool": 100,
    "bindCapAtChargen": 70,
    "strandLevels": 10,
    "extraStrandLevels": 3,
    "quote": "Select 2 Binds, 4 Strands, and 2 Thin Strands... Add +10 to each of your two chosen Bind skills... Spend the 100 Magic skill points among any of the five Binds. No Bind may be developed past 70... Add 10 levels of Strands among any of your chosen 4 Strands. Add three additional levels of Strands to any Strands except Thin Strands."
  },
  "shapingQuote": "Before it can be cast, a spell must be shaped by the following elements, each one contributing to its Total Cost (TC).",
  "masteryQuote": "Add together the Bind roll's ones die, the relevant Strand value, and any Thread result to find the caster's Mastery.",
  "masteryOnesDieQuote": "Remember a \u201c0\u201d on the ones die counts as 10",
  "wrmQuote": "The difference between the Mastery and the TC is called the Weave Reaction Modifier.",
  "mitigationQuote": "Each additional Resolve spent reduces the modifier by 1. Reducing the modifier to zero cancels the Weave Reaction.",
  "critFailQuote": "The spell is not cast. Spend 1 Resolve and immediately roll on the Weave Reaction Table, adding the spell's Magnitude cost to the result. Fades also gain 1 Fraying.",
  "armorTcQuote": "Initiative penalty of worn armor acts as a positive modifier to every spell's TC.",
  "fadeChargenStrands": 5,
  "fadeStrandStartQuote": "Start with a total of 5 levels among any Strands of your choice. A Fade may never have more than 7 in any Strand.",
  "fadeBindCap": 70,
  "fadeBindCapQuote": "A Fade can never develop any Bind skill past 70.",
  "newBindXp": 5,
  "newBindQuote": "If a Spellweaver or Fade doesn't yet have skill in a particular Bind, they may spend 5 XP to acquire it at a starting value of 10.",
  "roundingOutStrandCost": 5,
  "roundingOutQuote": "Allowed Strands may be improved for five bonus skill points per level, to a maximum of level 5 at character creation.",
  "savvyQuote": "Piety and Strand skills cannot be chosen as Savvy skills.",
  "weaveReactionQuote": "An uncontrolled spell must roll d20 + the Weave Reaction Modifier and consult the Weave Reaction Table",
  "fatigueOverflowQuote": "If his Resolve Track has no more open boxes to mark Fatigue, for every point of Fatigue he cannot take, he instead takes a \u201cWeave\u201d Wound of that value to a random location.",
  "threadDieQuote": "When using the Thread Die, roll it after a successful Bind roll, and gain whatever amount you roll as Mastery. If you roll a 1 or a 2, take that number as bonus Mastery, but reduce the Thread Die to the next lower die type. If a d6 Thread rolls a 1 or a 2, it is fully expended and crumbles to dust.",
  "threadLimitQuote": "You may use up to one Bind Thread and one Strand Thread in a single casting. Additional Threads of the same type never stack",
  "threadAfterSuccessQuote": "Threads are used only after a successful Bind roll (never on a failure).",
  "resolveFavorQuote": "You can spend Resolve as Favor (+10 per Resolve to a skill roll). As stated above, up to 3 Favor may be used on any one skill roll from any source, including Resolve.",
  "requisiteQuote": "having to use the lower value of the applicable Bind or Strand",
  "castingTimeQuote": "A spell with a Duration of 1 minute or less has a casting time of 1 action."
};
export const FRAYING_SYMPTOMS = [
  {
    "key": "flat10",
    "label": "10 Fraying points (regardless of Max Resolve)",
    "summary": "Subtle, deniable disturbances that might be passed off as fatigue or coincidence.",
    "q": "10 Fraying points (regardless of Max Resolve)",
    "signs": [
      "Your shadow lags behind or tilts slightly wrong.",
      "Strangers forget your name moments after hearing it.",
      "Your reflections ripple or appear subtly distorted.",
      "Your footprints fade away almost as soon as they're made."
    ]
  },
  {
    "key": "mr-5",
    "label": "Fraying >= Max Resolve - 5",
    "summary": "The wrongness can no longer be ignored by those nearby.",
    "q": "Fraying points \u2265 Max Resolve -5",
    "signs": [
      "Animals shy away, bark, or bolt from your presence.",
      "Written words about you blur or fade from pages.",
      "Colors look washed out when you enter a space.",
      "Companions swear you weren't there until you spoke."
    ]
  },
  {
    "key": "mr",
    "label": "Fraying >= Max Resolve",
    "summary": "Reality struggles to hold you in place; the unraveling is undeniable.",
    "q": "Fraying points \u2265 Max Resolve",
    "signs": [
      "Doubles of you are glimpsed in the corner of the eye.",
      "Dreams depict you as faceless or as a stranger.",
      "Patterns misalign: bricks, tiles, rugs subtly warp around you.",
      "Objects near you refuse to line up"
    ]
  },
  {
    "key": "mr+5",
    "label": "Fraying >= Max Resolve + 5",
    "summary": "The Weave is actively tugging your thread loose.",
    "q": "Fraying \u2265 Max Resolve +5",
    "signs": [
      "Your eyes look hollow or distant.",
      "Whole conversations with you vanish from memory after they end.",
      "Places you linger warp: candles drip upward, mirrors crack, walls bend, plants wither.",
      "You feel a constant physical snag in your chest, like a thread being pulled away."
    ]
  }
];
