/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class TheBrokenEmpiresActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't 
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    /* There is no `flags.thebrokenempires` in this system and nothing has ever
       written one -- that read was template boilerplate, assigned to a variable
       nothing then used. This comment used to record that the system ALSO used
       two different flag scopes, `tbe` and `the-broken-empires`, and that
       consolidating them was a real decision with a migration attached.
       Consolidated in v0.39.0: `TBE.FLAG_SCOPE` is the one namespace, the
       0.39.0 migration steps move the owned keys, and the split turned out to
       be hiding a live bug -- "tbe" is not a scope Foundry accepts, so the one
       file that used setFlag/getFlag rather than writing the path by hand
       (TBE: Funnel Roster) threw on every call. */

    /* Bulk & Initiative Penalty (Ch.9 p.141): "Add up the Bulk from each piece
     * of worn armor and divide by 3, rounding up. The result is the Initiative
     * penalty your armor causes you. This is only for worn armor."
     *
     * Derived here, on the actor, rather than in the sheet, because three
     * places needed the same number and each had its own copy: the sheet's
     * _prepareArmorPenalty(), TBE: Cast, and TBE: Finish Character. The
     * initiative formula registered in the init hook needs it too, and a roll
     * formula cannot call a sheet method. One owner, readable from anywhere
     * that can see the actor. */
    /* DERIVED-DATA RULE (CLAUDE.md): armorBulk, armorInitPenalty and
     * initiativeEffective below are EPHEMERAL. They are not in any schema
     * (defineSchema() in base-actor.mjs has no field named any of the
     * three), they are recomputed UNCONDITIONALLY every time this method
     * runs -- never "if not already set" -- and nothing may ever write to
     * `system.armorBulk`/`armorInitPenalty`/`initiativeEffective` through
     * actor.update(). Foundry calls this method after every data reset, so
     * even a stray persisted value in a world's save file is overwritten
     * the next time the actor loads; derived_data_check.mjs proves that by
     * seeding a wrong value first and asserting it doesn't survive. A new
     * derived field belongs here under the same rule, not as a schema
     * field with a default that quietly goes stale. */
    const num = (v, d = 0) => (Number.isFinite(Number(v)) ? Number(v) : d);
    const bulk = this.items
      .filter((i) => i.type === "armor" && i.system?.equipped !== false)
      .reduce((sum, i) => sum + num(i.system?.bulk, 0), 0);
    const penalty = Math.ceil(bulk / 3);
    this.system.armorBulk = bulk;
    this.system.armorInitPenalty = penalty;
    /* p.161: "If a roll takes a character's initiative below 0, the character
     * acts on the negative value" -- so this is deliberately not clamped. */
    this.system.initiativeEffective = num(this.system.initiative, 0) - penalty;
  }

  /**
   * 
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic 
   * approach is useful when you have actors & items that share a parent Document, 
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * Convert the actor document to a plain object.
   * 
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   * 
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

}
